language: objective-c
osx_image: xcode9.2
rvm: 2.5.0
cache:
  - bundler
  - cocoapods
install:
  - gem update bundler
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install
script: bundle exec fastlane ci
after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
  slack:
    secure: giaI5posq/yBzeX5Rrpvs94j4fJkKCQEjARQVqK/v+tZopjoXrUCPJ3GmDh6zXJcO3swk/IvXPxwC0hFgAsrBwl7DVs7Oks2YbB4X3gVr/eB81D9u+e3wvc+W6ic55lTYRa9lLY+y3aarn1baMLrDPf5iwljj40s2Apmt3knOgL4v44WibuCOAyE8fr1cdZjzAHtfGZn6j/ZiYZgipYLtjEIN155+3Qf6dUHFHWP73x0aonUxPeojRH3xEusav5DDo1bFxXR2+TXad+Dpr62+Aetf4km6wj8Hp5Bi9+vLkCQVFXXGGQuCgSCW11kdb/SghQTrB+vdZ7XayJ5361A7uopF9VBAsiC7eHGWXgKrjZNkmg9gKL+ZbeR90YUBtRGFx2X8uckcSANF6laEMgNOM/Qw3EnNa1+UIX/UXweczViZB2wP/yg0yKaNo/MIS39oM2SOgC4K1xDw0Aq5mgqVhxLTQEI/nHqBWbG1FZTLGJlYBMKsyBggeXmZjjU8JlgJXMaQrui8Rf0SsIvS/qKbsWxyCxtln8oC0h/SKbRaOCzfm9Jffoz+xyC4FysPrYdGN6qxg7g+YH5dvc1Fq2ldSEoUPKqQYofhj7vMS7crA2kMGBu47T67XX5rsboRg66TICdqi557gDnONkN4VKuAPYL33JA6JXdfHjXpiqAsu8=
