
lane :default do |options|
    test
    # Deploy if it's in master branch after a pull request
    if ENV["TRAVIS_BRANCH"] == "master" && ENV["TRAVIS_PULL_REQUEST"] == "false"
        deploy
    end
end

lane :test do |options|
    danger
    run_tests
    codecov
end

lane :deploy do |options|
    increment_build_number(build_number: Time.now.getutc.strftime("%Y%m%d%H%M%S%L"))
end
