
lane :default do |options|
    # Check if it's in master branch after a pull request
    if ENV["TRAVIS_BRANCH"] == "master" && ENV["TRAVIS_PULL_REQUEST"] == "false"
        deploy
    else
        test
    end
end

lane :deploy do |options|
    UI.message "Deploy!!!"
end

lane :test do |options|
    UI.message "Test!!!"
end
